### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by TAKANOME-DEV**
When someone create a new issue, this screen below will be display:

new_issue

If bug is choosed, this screen down below will be display:

bug_report

### CODE REVIEW

**Comment by TAKANOME-DEV** [comment]
Docs updated due to #22, PR up to date

**Review by MizouziE — APPROVED** [review]
This is absolutely amazing! thank you very much and I am really looking forward to how much easier this is going to make it for people in the future.

One thing you've pointed out is that I may need to add a prettier config file 😂😂

**Comment by TAKANOME-DEV** [comment]
😄 Yeah it would be great if we you can add prettier to format the code

**Comment by MizouziE** [comment]
Gonna make this it's own issue (Prettier)

**Pull request merged**
