### PR TITLE
feat: move sources and twitter accounts into a data folder

### PR DESCRIPTION
**Pull request by TAKANOME-DEV**
Prettier format my code on save, that's why it add semicolons and so one

### CODE REVIEW

**Comment by TAKANOME-DEV** [comment]
Merge conflict resolved 😃

**Comment by TAKANOME-DEV** [comment]
Pull latest changes and resolve another merge conflict

**Review by MizouziE — CHANGES_REQUESTED** [review]
please update your local `.gitignore` to leave out the `.dccache` file from the PR and push a fresh commit to remove it

**Comment by TAKANOME-DEV** [comment]
My bad, thanks.
PR updated

**Review by MizouziE — APPROVED** [review]
Perfect! Cheers 🍻

**Comment by MizouziE** [comment]
Hey @TAKANOME-DEV just an FYI
the commented out lines in the `data/sources.json` file caused a break when I deployed, I should have tested and spotted that before 🤦‍♂️

I just removed the commented out lines and redeployed and it's all working perfect now though 🙌

**Pull request merged**
