### PR TITLE
Trim blanks at both ends of title.

### PR DESCRIPTION
**Pull request by OakenSushi**
### What does this PR do?
Issue #5

### CODE REVIEW

**Comment by MizouziE** [comment]
Hi @OakenSushi ,

This is a step in the right direction, which is great! There are a couple of things I'd like you to take a look at before I can merge.

- The `trim()` method only works when the whitespace reaches the start/end of the line, and the problem I had was that the ends were often blocked with "\n" characters and *then* a huge white space. I would suggest a `replace()` function with a RegExp before the `trim()` like in the below: 
```js
            $('a:contains("energy")', html).each(function () {
                const title = $(this).text().replace(/(\r\n|\n|\r)/gm, "").trim()
                const url = $(this).attr('href')

                articles.push({
                    title,
                    url: source.base + url,
                    source: source.name
                })
            })
```
- Once that is working properly, as I think it should, there is also one other place within the `app.get('/news/:sourceId',...)` route that will require the same additions as it is more or less the exact same logic for creating the array for that route.

Great work and please let me know if I can clarify anything!

Thanks again!

Sam

**Review by MizouziE — CHANGES_REQUESTED** [review]
Please see comment on PR 👍

**Comment by OakenSushi** [comment]
@MizouziE 
Thanks for the review!
I have checked your comment and corrected it.

**Review by MizouziE — APPROVED** [review]
Brilliant! 🙌 

Thanks very much for your contribution. When I create the contributors list file, I will be sure to include you!

**Pull request merged**
